version: 0.2

# run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    # run-as: root
    commands:
      - npm install
      - echo "Pre build initiated"
    #   - command
  build:
    # run-as: root
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Running post deployment"
  artifacts:
    files:
      -"**/*"
  discard-paths: no
  base-directory: dist
    finally:
      - echo "Done"
    #   - command
# artifacts:
#   files:
#     - location
#     - location
#     - name
#   discard-paths: yes
#   base-directory: location
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
# cache:
#   paths:
#     - path
#     - path
