version: 0.2

# run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    # run-as: root
    commands:
      - cd ./client
      - npm install
      - cd ..
      - echo "Pre build initiated"
    finally:
      - echo Pre Build Completed
    #   - command
  build:
    # run-as: root
    commands:
      - cd ./client 
      - npm run build
    finally:
      - echo Build Phase completed
  post_build:
    commands:
      - echo "Running post deployment"
      - aws s3 sync ./client/build s3://sunnyones.com
    finally:
      - echo "Done"

