version: 0.2

# run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 10

  pre_build:
    # run-as: root
    commands:
      - echo "Pre build initiated"
    finally:
      - echo "Pre build Done"
    #   - command
  build:
    # run-as: root
    commands:
      - npm install
      - npm audit fix
      - npm run-script build
    # finally:
    #   - command
    #   - command
  post_build:
    commands:
      - echo "Running post deployment"
    finally:
      - echo "Done"
    #   - command
# artifacts:
#   files:
#     - location
#     - location
#     - name
#   discard-paths: yes
#   base-directory: location
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
# cache:
#   paths:
#     - path
#     - path
