version: 0.2

# run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    # run-as: root
    commands:
      - yum install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
      - cd ./client
      - npm install
      - cd ..
      - echo "Pre build initiated"
    finally:
      - echo Pre Build Completed
    #   - command
  build:
    # run-as: root
    commands:
      - cd ./client
      - node_modules/.bin/cypress run
      - npm run build
    finally:
      - echo Build Phase completed
  post_build:
    commands:
      - echo "Running post deployment"
      - aws s3 sync ./build s3://sunnyones.com
    finally:
      - echo "Dones"
