version: 0.2
# run-as: root
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    # run-as: root
    commands:
      # - yum -y install xorg-x11-server-Xvfb.x86_64 gtk3-devel.x86_64 libnotify-devel.x86_64 GConf2-3.2.6-8.amzn2.0.2.x86_64 nss-3.44.0-4.amzn2.0.2.x86_64 libXScrnSaver.x86_64 alsa-lib-1.1.4.1-2.amzn2.x86_64
      - cd ./client
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
      - npm install
      - npm install -g wait-on
      # - npm install -g start-server-and-test
      - cd ..
      - echo "Pre build initiated"
    finally:
      - echo Pre Build Completed
    #   - command
  build:
    # run-as: root
    commands:
      - cd ./client
      - npm start & npx wait-on http://localhost:3000
      - npx cypress run
    finally:
      - echo Build Phase completed
  post_build:
    commands:
      - echo "Running post deployment"
      - aws s3 sync ./build s3://sunnyones.com
    finally:
      - echo "Dones"
