version: 0.2


 phases:
  install:
    runtime-versions:
    	nodejs: 10
    commands:	
      - echo Running install phase	
    finally:	
      - echo Executing install phase finally	
  pre_build:	
    commands:	
      - echo Running pre_build phase	
    finally:	
      - echo Executing pre_build phase finally	
  build:	  build:
    commands:	    commands:
      - echo Running build phase	      - echo Running build phase
    finally:	
      - echo Executing build phase finally	
  post_build:	
    commands:	
      - echo Running post_build phase	
    finally:	
      - echo Executing post_build phase	
artifacts:	artifacts:
  files:	  files:
    - '**/*' 