version: 0.2

# run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 10

  pre_build:
    # run-as: root
    commands:
      - echo "Pre build initiated"
    finally:
      - echo "Pre build Done"
    #   - command
  build:
    # run-as: root
    commands:
      - npm install
      - npm audit fix
      - npm run-script build
      - aws s3 sync --delete build/. "http://react-application-teachers.s3.amazonaws.com" --acl public-read --cache-control max-age=31536000
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths /index.html /* /fonts/* /images/* /javascripts/* /stylesheets/* /favicon.ico
    # finally:
    #   - command
    #   - command
  post_build:
    commands:
      - echo "Running post deployment"
    finally:
      - echo "Done"
    #   - command
# artifacts:
#   files:
#     - location
#     - location
#     - name
#   discard-paths: yes
#   base-directory: location
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
# cache:
#   paths:
#     - path
#     - path
